In [1]:
import os
import re
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

BASE = "https://datos.madrid.es/dataset/300352-0-meteorologicos-horarios/downloads"
OUT_DIR = "madrid_weather_2023_csv"
os.makedirs(OUT_DIR, exist_ok=True)

html = requests.get(BASE, timeout=30).text
soup = BeautifulSoup(html, "html.parser")

links = []
for a in soup.find_all("a", href=True):
    text = " ".join(a.get_text(" ", strip=True).split())
    href = urljoin(BASE, a["href"])

    if (
        "2023" in text
        and "CSV Datos meteorológicos" in text
        and href.endswith("-csv")
    ):
        # Convert resource page URL to actual CSV download URL
        resource_id = href.rstrip("/").split("/")[-1]
        download_url = f"{href}/download/{resource_id}.csv"
        links.append((text, download_url))

print(f"Found {len(links)} CSV files")

for i, (title, url) in enumerate(links, start=1):
    filename = f"2023_{i:02d}.csv"
    path = os.path.join(OUT_DIR, filename)

    print("Downloading:", title)
    r = requests.get(url, timeout=60)
    r.raise_for_status()

    with open(path, "wb") as f:
        f.write(r.content)

print("Done.")

Found 12 CSV files
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Enero Descargado 2.429 veces. Tamaño: 301.4 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Febrero Descargado 2.381 veces. Tamaño: 434.5 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Marzo Descargado 2.298 veces. Tamaño: 490.9 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Abril Descargado 2.289 veces. Tamaño: 473.5 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Mayo Descargado 2.200 veces. Tamaño: 479.8 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Junio Descargado 2.099 veces. Tamaño: 457.9 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Julio Descargado 2.036 veces. Tamaño: 475.0 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Agosto Descargado 1.992 veces. Tamaño: 479.5 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Septiembre Descargado 1.941 veces. Tamaño: 473.8 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Octubre Descargado 1.961 veces. Tamaño: 484.5 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. Noviembre Descargado 1.833 veces. Tamaño: 463.0 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2023. DIciembre Descargado 1.818 veces. Tamaño: 485.3 KB
Done.

In [2]:
YEAR = "2024"
BASE = "https://datos.madrid.es/dataset/300352-0-meteorologicos-horarios/downloads"
OUT_DIR = f"madrid_weather_{YEAR}_csv"
os.makedirs(OUT_DIR, exist_ok=True)

html = requests.get(BASE, timeout=30).text
soup = BeautifulSoup(html, "html.parser")

links = []
for a in soup.find_all("a", href=True):
    text = " ".join(a.get_text(" ", strip=True).split())
    href = urljoin(BASE, a["href"])

    if (
        YEAR in text
        and "CSV Datos meteorológicos" in text
        and href.endswith("-csv")
    ):
        resource_id = href.rstrip("/").split("/")[-1]
        download_url = f"{href}/download/{resource_id}.csv"
        links.append((text, download_url))

print(f"Found {len(links)} CSV files for {YEAR}")

for i, (title, url) in enumerate(links, start=1):
    filename = f"{YEAR}_{i:02d}.csv"
    path = os.path.join(OUT_DIR, filename)

    print("Downloading:", title)
    r = requests.get(url, timeout=60)
    r.raise_for_status()

    with open(path, "wb") as f:
        f.write(r.content)

print("Done.")

Found 12 CSV files for 2024
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Enero Descargado 1.725 veces. Tamaño: 485.4 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Febrero Descargado 1.674 veces. Tamaño: 444.5 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Marzo Descargado 1.628 veces. Tamaño: 486.8 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Abril Descargado 1.600 veces. Tamaño: 445.9 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Mayo Descargado 1.611 veces. Tamaño: 493.6 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Junio Descargado 1.635 veces. Tamaño: 481.4 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Julio Descargado 1.569 veces. Tamaño: 498.1 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Agosto Descargado 1.609 veces. Tamaño: 495.4 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Septiembre Descargado 1.535 veces. Tamaño: 475.5 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Octubre Descargado 1.531 veces. Tamaño: 490.6 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Noviembre Descargado 1.470 veces. Tamaño: 459.3 KB
Downloading: CSV Datos meteorológicos. Datos horarios desde 2019. 2024. Diciembre Descargado 1.617 veces. Tamaño: 470.2 KB
Done.

In [3]:
import pandas as pd
from pathlib import Path

files = (
    sorted(Path("madrid_weather_2023_csv").glob("*.csv"))
    + sorted(Path("madrid_weather_2024_csv").glob("*.csv"))
    + [Path("2025_2026.csv")]
)

for file in files:
    df = pd.read_csv(file, sep=";", nrows=0)
    print(file.name)
    print(list(df.columns))
    print("-" * 50)

2023_01.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_02.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_03.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_04.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_05.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_06.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_07.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_08.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_09.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_10.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_11.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2023_12.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_01.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_02.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_03.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_04.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_05.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_06.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_07.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_08.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_09.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_10.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_11.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2024_12.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------
2025_2026.csv
['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO', 'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04', 'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09', 'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14', 'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19', 'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24', 'V24']
--------------------------------------------------

In [4]:
import pandas as pd
from pathlib import Path

files = []

# 2023 files
files.extend(sorted(Path("madrid_weather_2023_csv").glob("*.csv")))

# 2024 files
files.extend(sorted(Path("madrid_weather_2024_csv").glob("*.csv")))

# 2025-2026 file
files.append(Path("2025_2026.csv"))

print(f"Found {len(files)} files")

dfs = []

for file in files:
    print(f"Reading {file}")

    try:
        df = pd.read_csv(
            file,
            sep=";",        
            encoding="utf-8"
        )

        df["source_file"] = file.name
        dfs.append(df)

    except Exception as e:
        print(f"Error reading {file}: {e}")

combined = pd.concat(dfs, ignore_index=True)

print(f"Total rows: {len(combined):,}")
print(f"Total columns: {len(combined.columns)}")

combined.to_csv(
    "madrid_weather_2023_2026.csv",
    index=False,
    encoding="utf-8"
)

print("Saved as madrid_weather_2023_2026.csv")

Found 25 files
Reading madrid_weather_2023_csv/2023_01.csv
Reading madrid_weather_2023_csv/2023_02.csv
Reading madrid_weather_2023_csv/2023_03.csv
Reading madrid_weather_2023_csv/2023_04.csv
Reading madrid_weather_2023_csv/2023_05.csv
Reading madrid_weather_2023_csv/2023_06.csv
Reading madrid_weather_2023_csv/2023_07.csv
Reading madrid_weather_2023_csv/2023_08.csv
Reading madrid_weather_2023_csv/2023_09.csv
Reading madrid_weather_2023_csv/2023_10.csv
Reading madrid_weather_2023_csv/2023_11.csv
Reading madrid_weather_2023_csv/2023_12.csv
Reading madrid_weather_2024_csv/2024_01.csv
Reading madrid_weather_2024_csv/2024_02.csv
Reading madrid_weather_2024_csv/2024_03.csv
Reading madrid_weather_2024_csv/2024_04.csv
Reading madrid_weather_2024_csv/2024_05.csv
Reading madrid_weather_2024_csv/2024_06.csv
Reading madrid_weather_2024_csv/2024_07.csv
Reading madrid_weather_2024_csv/2024_08.csv
Reading madrid_weather_2024_csv/2024_09.csv
Reading madrid_weather_2024_csv/2024_10.csv
Reading madrid_weather_2024_csv/2024_11.csv
Reading madrid_weather_2024_csv/2024_12.csv
Reading 2025_2026.csv
Total rows: 111,149
Total columns: 57
Saved as madrid_weather_2023_2026.csv

In [5]:
import pandas as pd

df = pd.read_csv("madrid_weather_2023_2026.csv")

print(df.shape)     
print(df.columns)   
print(df.info())

(111149, 57)
Index(['PROVINCIA', 'MUNICIPIO', 'ESTACION', 'MAGNITUD', 'PUNTO_MUESTREO',
       'ANO', 'MES', 'DIA', 'H01', 'V01', 'H02', 'V02', 'H03', 'V03', 'H04',
       'V04', 'H05', 'V05', 'H06', 'V06', 'H07', 'V07', 'H08', 'V08', 'H09',
       'V09', 'H10', 'V10', 'H11', 'V11', 'H12', 'V12', 'H13', 'V13', 'H14',
       'V14', 'H15', 'V15', 'H16', 'V16', 'H17', 'V17', 'H18', 'V18', 'H19',
       'V19', 'H20', 'V20', 'H21', 'V21', 'H22', 'V22', 'H23', 'V23', 'H24',
       'V24', 'source_file'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111149 entries, 0 to 111148
Data columns (total 57 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PROVINCIA       111149 non-null  int64
 1   MUNICIPIO       111149 non-null  int64
 2   ESTACION        111149 non-null  int64
 3   MAGNITUD        111149 non-null  int64
 4   PUNTO_MUESTREO  66061 non-null   object
 5   ANO             111149 non-null  int64
 6   MES             111149 non-null  int64
 7   DIA             111149 non-null  int64
 8   H01             111149 non-null  float64
 9   V01             111149 non-null  object
 10  H02             111149 non-null  float64
 11  V02             111149 non-null  object
 12  H03             111149 non-null  float64
 13  V03             111149 non-null  object
 14  H04             111149 non-null  float64
 15  V04             111149 non-null  object
 16  H05             111149 non-null  float64
 17  V05             111149 non-null  object
 18  H06             111149 non-null  float64
 19  V06             111149 non-null  object
 20  H07             111149 non-null  float64
 21  V07             111149 non-null  object
 22  H08             111149 non-null  float64
 23  V08             111149 non-null  object
 24  H09             111149 non-null  float64
 25  V09             111149 non-null  object
 26  H10             111149 non-null  float64
 27  V10             111149 non-null  object
 28  H11             111149 non-null  float64
 29  V11             111149 non-null  object
 30  H12             111149 non-null  float64
 31  V12             111149 non-null  object
 32  H13             111149 non-null  float64
 33  V13             111149 non-null  object
 34  H14             111149 non-null  float64
 35  V14             111149 non-null  object
 36  H15             111149 non-null  float64
 37  V15             111149 non-null  object
 38  H16             111149 non-null  float64
 39  V16             111149 non-null  object
 40  H17             111149 non-null  float64
 41  V17             111149 non-null  object
 42  H18             111149 non-null  float64
 43  V18             111149 non-null  object
 44  H19             111149 non-null  float64
 45  V19             111149 non-null  object
 46  H20             111149 non-null  float64
 47  V20             111149 non-null  object
 48  H21             111149 non-null  float64
 49  V21             111149 non-null  object
 50  H22             111149 non-null  float64
 51  V22             111149 non-null  object
 52  H23             111149 non-null  float64
 53  V23             111149 non-null  object
 54  H24             111149 non-null  float64
 55  V24             111149 non-null  object
 56  source_file     111149 non-null  object
dtypes: float64(24), int64(7), object(26)
memory usage: 48.3+ MB
None

/var/folders/rd/92q19lbj5xxgb_pn8_lyp78m0000gn/T/ipykernel_3287/1783780256.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("madrid_weather_2023_2026.csv")

In [6]:
import pandas as pd

df = pd.read_csv(
    "madrid_weather_2023_2026.csv",
    low_memory=False
)

column_mapping = {
    "PROVINCIA": "PROVINCE",
    "MUNICIPIO": "MUNICIPALITY",
    "ESTACION": "STATION",
    "MAGNITUD": "MAGNITUDE",
    "PUNTO_MUESTREO": "SAMPLING_POINT",
    "ANO": "YEAR",
    "MES": "MONTH",
    "DIA": "DAY"
}

for i in range(1, 25):
    column_mapping[f"H{i:02d}"] = f"HOUR_{i:02d}"
    column_mapping[f"V{i:02d}"] = f"VALIDITY_{i:02d}"
    
df.rename(columns=column_mapping, inplace=True)

df.to_csv(
    "madrid_weather_2023_2026_english.csv",
    index=False
)

print("Saved as madrid_weather_2023_2026_english.csv")

Saved as madrid_weather_2023_2026_english.csv

In [7]:
import pandas as pd

stations = pd.read_csv(
    "StationsLocation_Madrid.csv",
    sep=";",      
    low_memory=False
)

print(stations.shape)
print(stations.columns.tolist())
print(stations.head())

(26, 23)
['CÓDIGO', 'CÓDIGO_CORTO', 'ESTACION', 'DIRECCION', 'LONGITUD_ETRS89', 'LATITUD_ETRS89', 'ALTITUD', 'VV (81)', 'DV (82)', 'T (83)', 'HR (86)', 'PB (87)', 'RS (88)', 'P (89)', 'COD_VIA', 'VIA_CLASE', 'VIA_PAR', 'VIA_NOMBRE', 'NUM_VIA', 'COORDENADA_X_ETRS89', 'COORDENADA_Y_ETRS89', 'LONGITUD', 'LATITUD']
     CÓDIGO  CÓDIGO_CORTO          ESTACION  \
0  28079004             4      Plaza España
1  28079008             8  Escuelas Aguirre
2  28079016            16      Arturo Soria
3  28079018            18         Farolillo
4  28079024            24     Casa de Campo

                                           DIRECCION LONGITUD_ETRS89  \
0                                    Plaza de España    3°42'43.91"O
1                    Entre C/ Alcalá y C/ O’ Donell     3°40'56.22"O
2  C/ Arturo Soria  esq. C/  Vizconde de los Asilos     3°38'21.17"O
3                        Calle Farolillo - C/Ervigio    3°43'54.61"O
4           Casa de Campo  (Terminal del Teleférico)    3°44'50.44"O

  LATITUD_ETRS89  ALTITUD VV (81) DV (82) T (83)  ... P (89)   COD_VIA  \
0  40°25'25.98"N      637     NaN     NaN      X  ...    NaN  273600.0
1  40°25'17.63"N      672     NaN     NaN      X  ...    NaN   18900.0
2  40°26'24.20"N      695     NaN     NaN      X  ...    NaN  798700.0
3  40°23'41.22"N      625     NaN     NaN      X  ...    NaN    1903.0
4   40°25'9.69"N      645       X       X      X  ...      X  905219.0

   VIA_CLASE VIA_PAR              VIA_NOMBRE NUM_VIA COORDENADA_X_ETRS89  \
0      PLAZA      DE                  ESPAÑA     NaN         439579,3291
1      CALLE      DE                  ALCALA     NaN         442117,2366
2      CALLE     DEL  VIZCONDE DE LOS ASILOS     NaN         445786,1729
3      CALLE     DEL               FAROLILLO     NaN         437891,6961
4  CARRETERA     DEL              TELEFERICO     NaN         436598,5637

  COORDENADA_Y_ETRS89  LONGITUD    LATITUD
0         4475049,263 -3.712257  40.423882
1         4474770,696 -3.682316  40.421553
2         4476796,019 -3.639242  40.440046
3         4471832,769 -3.731836  40.394782
4         4474571,618 -3.747345  40.419358

[5 rows x 23 columns]

In [15]:
import pandas as pd

stations = pd.read_csv(
    "madrid_weather_2023_2026_English.csv",
    sep=";",      
    low_memory=False
)
print(stations.head())

  PROVINCE,MUNICIPALITY,STATION,MAGNITUDE,SAMPLING_POINT,YEAR,MONTH,DAY,HOUR_01,VALIDITY_01,HOUR_02,VALIDITY_02,HOUR_03,VALIDITY_03,HOUR_04,VALIDITY_04,HOUR_05,VALIDITY_05,HOUR_06,VALIDITY_06,HOUR_07,VALIDITY_07,HOUR_08,VALIDITY_08,HOUR_09,VALIDITY_09,HOUR_10,VALIDITY_10,HOUR_11,VALIDITY_11,HOUR_12,VALIDITY_12,HOUR_13,VALIDITY_13,HOUR_14,VALIDITY_14,HOUR_15,VALIDITY_15,HOUR_16,VALIDITY_16,HOUR_17,VALIDITY_17,HOUR_18,VALIDITY_18,HOUR_19,VALIDITY_19,HOUR_20,VALIDITY_20,HOUR_21,VALIDITY_21,HOUR_22,VALIDITY_22,HOUR_23,VALIDITY_23,HOUR_24,VALIDITY_24,source_file
0  28,79,108,81,28079108_81_98,2023,1,1,0.67,V,1....
1  28,79,108,81,28079108_81_98,2023,1,2,0.77,V,0....
2  28,79,108,81,28079108_81_98,2023,1,3,0.3,V,0.5...
3  28,79,108,81,28079108_81_98,2023,1,4,0.5,V,0.3...
4  28,79,108,81,28079108_81_98,2023,1,5,0.18,V,0....

In [11]:
import pandas as pd

stations = pd.read_csv(
    "StationsLocation_Madrid.csv",
    sep=";",
    low_memory=False
)

column_mapping = {
    "CÓDIGO": "STATION_CODE",
    "CÓDIGO_CORTO": "STATION_ID",
    "ESTACION": "STATION_NAME",
    "DIRECCION": "ADDRESS",
    "LONGITUD_ETRS89": "LONGITUDE_ETRS89",
    "LATITUD_ETRS89": "LATITUDE_ETRS89",
    "ALTITUD": "ALTITUDE",
    "VV (81)": "WIND_SPEED_81",
    "DV (82)": "WIND_DIRECTION_82",
    "T (83)": "TEMPERATURE_83",
    "HR (86)": "RELATIVE_HUMIDITY_86",
    "PB (87)": "BAROMETRIC_PRESSURE_87",
    "RS (88)": "SOLAR_RADIATION_88",
    "P (89)": "PRECIPITATION_89",
    "COD_VIA": "ROAD_CODE",
    "VIA_CLASE": "ROAD_TYPE",
    "VIA_PAR": "ROAD_PREFIX",
    "VIA_NOMBRE": "ROAD_NAME",
    "NUM_VIA": "ROAD_NUMBER",
    "COORDENADA_X_ETRS89": "X_COORD_ETRS89",
    "COORDENADA_Y_ETRS89": "Y_COORD_ETRS89",
    "LONGITUD": "LONGITUDE",
    "LATITUD": "LATITUDE"
}

stations.rename(columns=column_mapping, inplace=True)

stations.to_csv(
    "StationsLocation_Madrid_English.csv",
    index=False,
    encoding="utf-8"
)

print("Saved as StationsLocation_Madrid_English.csv")
print(stations.columns.tolist())

Saved as StationsLocation_Madrid_English.csv
['STATION_CODE', 'STATION_ID', 'STATION_NAME', 'ADDRESS', 'LONGITUDE_ETRS89', 'LATITUDE_ETRS89', 'ALTITUDE', 'WIND_SPEED_81', 'WIND_DIRECTION_82', 'TEMPERATURE_83', 'RELATIVE_HUMIDITY_86', 'BAROMETRIC_PRESSURE_87', 'SOLAR_RADIATION_88', 'PRECIPITATION_89', 'ROAD_CODE', 'ROAD_TYPE', 'ROAD_PREFIX', 'ROAD_NAME', 'ROAD_NUMBER', 'X_COORD_ETRS89', 'Y_COORD_ETRS89', 'LONGITUDE', 'LATITUDE']

In [14]:
import pandas as pd

stations = pd.read_csv(
    "StationsLocation_Madrid_English.csv",
    sep=";",      
    low_memory=False
)


print(stations.head())

  STATION_CODE,STATION_ID,STATION_NAME,ADDRESS,LONGITUDE_ETRS89,LATITUDE_ETRS89,ALTITUDE,WIND_SPEED_81,WIND_DIRECTION_82,TEMPERATURE_83,RELATIVE_HUMIDITY_86,BAROMETRIC_PRESSURE_87,SOLAR_RADIATION_88,PRECIPITATION_89,ROAD_CODE,ROAD_TYPE,ROAD_PREFIX,ROAD_NAME,ROAD_NUMBER,X_COORD_ETRS89,Y_COORD_ETRS89,LONGITUDE,LATITUDE
0  28079004,4,Plaza España,Plaza de España,"3°42'...
1  28079008,8,Escuelas Aguirre,Entre C/ Alcalá y ...
2  28079016,16,Arturo Soria,C/ Arturo Soria  esq....
3  28079018,18,Farolillo,Calle Farolillo - C/Ervi...
4  28079024,24,Casa de Campo,Casa de Campo  (Term...

In [20]:
import pandas as pd

weather = pd.read_csv("madrid_weather_2023_2026_english.csv", low_memory=False)
stations = pd.read_csv("StationsLocation_Madrid_English.csv", low_memory=False)

stations_small = stations[
    [
        "STATION_CODE",
        "STATION_ID",
        "STATION_NAME",
        "ALTITUDE",
        "LONGITUDE",
        "LATITUDE"
    ]
].copy()

merged = weather.merge(
    stations_small,
    left_on="STATION",
    right_on="STATION_ID",
    how="left"
)

merged.drop(columns=["STATION_ID"], inplace=True)

merged.to_csv(
    "madrid_weather_2023_2026_with_station_location.csv",
    index=False
)

print(merged.shape)
print("Saved successfully")

(111149, 62)
Saved successfully

In [22]:
import pandas as pd

stations = pd.read_csv(
    "madrid_weather_2023_2026_with_station_location.csv",
    sep=";",      
    low_memory=False
)

print(stations.head())
print("Weather columns:", len(weather.columns))
print("Station columns:", len(stations_small.columns))
print("Merged columns:", len(merged.columns))

  PROVINCE,MUNICIPALITY,STATION,MAGNITUDE,SAMPLING_POINT,YEAR,MONTH,DAY,HOUR_01,VALIDITY_01,HOUR_02,VALIDITY_02,HOUR_03,VALIDITY_03,HOUR_04,VALIDITY_04,HOUR_05,VALIDITY_05,HOUR_06,VALIDITY_06,HOUR_07,VALIDITY_07,HOUR_08,VALIDITY_08,HOUR_09,VALIDITY_09,HOUR_10,VALIDITY_10,HOUR_11,VALIDITY_11,HOUR_12,VALIDITY_12,HOUR_13,VALIDITY_13,HOUR_14,VALIDITY_14,HOUR_15,VALIDITY_15,HOUR_16,VALIDITY_16,HOUR_17,VALIDITY_17,HOUR_18,VALIDITY_18,HOUR_19,VALIDITY_19,HOUR_20,VALIDITY_20,HOUR_21,VALIDITY_21,HOUR_22,VALIDITY_22,HOUR_23,VALIDITY_23,HOUR_24,VALIDITY_24,source_file,STATION_CODE,STATION_NAME,ALTITUDE,LONGITUDE,LATITUDE
0  28,79,108,81,28079108_81_98,2023,1,1,0.67,V,1....
1  28,79,108,81,28079108_81_98,2023,1,2,0.77,V,0....
2  28,79,108,81,28079108_81_98,2023,1,3,0.3,V,0.5...
3  28,79,108,81,28079108_81_98,2023,1,4,0.5,V,0.3...
4  28,79,108,81,28079108_81_98,2023,1,5,0.18,V,0....
Weather columns: 57
Station columns: 6
Merged columns: 62

In [24]:
import pandas as pd

df = pd.read_csv(
    "madrid_weather_2023_2026_with_station_location.csv",
    low_memory=False
)

magnitude_map = {
    81: "WIND SPEED",
    82: "WIND DIRECTION",
    83: "TEMPERATURE",
    86: "RELATIVE HUMIDITY",
    87: "BAROMETRIC PRESSURE",
    88: "SOLAR RADIATION",
    89: "PRECIPITATION"
}

df["MAGNITUDE_NAME"] = df["MAGNITUDE"].map(magnitude_map)

cols = df.columns.tolist()
cols.remove("MAGNITUDE_NAME")

magnitude_index = cols.index("MAGNITUDE")
cols.insert(magnitude_index + 1, "MAGNITUDE_NAME")

df = df[cols]

df.to_csv(
    "madrid_weather_2023_2026_with_station_location.csv",
    index=False
)

print("Saved successfully")
print(df[["MAGNITUDE", "MAGNITUDE_NAME"]].drop_duplicates().sort_values("MAGNITUDE"))
print(df.head())

Saved successfully
     MAGNITUDE       MAGNITUDE_NAME
0           81           WIND SPEED
31          82       WIND DIRECTION
62          83          TEMPERATURE
93          86    RELATIVE HUMIDITY
124         87  BAROMETRIC PRESSURE
155         88      SOLAR RADIATION
186         89        PRECIPITATION
   PROVINCE  MUNICIPALITY  STATION  MAGNITUDE MAGNITUDE_NAME  SAMPLING_POINT  \
0        28            79      108         81     WIND SPEED  28079108_81_98
1        28            79      108         81     WIND SPEED  28079108_81_98
2        28            79      108         81     WIND SPEED  28079108_81_98
3        28            79      108         81     WIND SPEED  28079108_81_98
4        28            79      108         81     WIND SPEED  28079108_81_98

   YEAR  MONTH  DAY  HOUR_01  ... HOUR_23  VALIDITY_23 HOUR_24  VALIDITY_24  \
0  2023      1    1     0.67  ...    0.30            V    0.40            V
1  2023      1    2     0.77  ...    0.20            V    0.37            V
2  2023      1    3     0.30  ...    0.02            V    0.13            V
3  2023      1    4     0.50  ...    0.00            V    0.10            V
4  2023      1    5     0.18  ...    0.10            V    0.35            V

   source_file  STATION_CODE STATION_NAME  ALTITUDE LONGITUDE   LATITUDE
0  2023_01.csv      28079108   Peñagrande       659 -3.717237  40.476944
1  2023_01.csv      28079108   Peñagrande       659 -3.717237  40.476944
2  2023_01.csv      28079108   Peñagrande       659 -3.717237  40.476944
3  2023_01.csv      28079108   Peñagrande       659 -3.717237  40.476944
4  2023_01.csv      28079108   Peñagrande       659 -3.717237  40.476944

[5 rows x 63 columns]

In [25]:
import pandas as pd

calendar = pd.read_csv(
    "CalendarData.csv",
    sep=";",
    low_memory=False
)

print(calendar.columns.tolist())
print(calendar.head(10))

['Dia', 'Dia_semana', 'laborable / festivo / domingo festivo', 'Tipo de Festivo', 'Festividad']
          Dia Dia_semana laborable / festivo / domingo festivo  \
0  01/01/2013     martes                               festivo
1  02/01/2013  miercoles                             laborable
2  03/01/2013     jueves                             laborable
3  04/01/2013    viernes                             laborable
4  05/01/2013     sabado                                sabado
5  06/01/2013    domingo                               domingo
6  07/01/2013      lunes                               festivo
7  08/01/2013     martes                             laborable
8  09/01/2013  miercoles                             laborable
9  10/01/2013     jueves                             laborable

    Tipo de Festivo                         Festividad
0  Festivo nacional                          Año Nuevo
1               NaN                                NaN
2               NaN                                NaN
3               NaN                                NaN
4               NaN                                NaN
5               NaN                                NaN
6  Festivo nacional  Traslado de la Epifanía del Señor
7               NaN                                NaN
8               NaN                                NaN
9               NaN                                NaN

In [30]:
import pandas as pd

weather = pd.read_csv(
    "madrid_weather_2023_2026_with_station_location.csv",
    low_memory=False
)

calendar = pd.read_csv(
    "CalendarData.csv",
    sep=";",
    low_memory=False
)

# Rename calendar columns to English
calendar.rename(
    columns={
        "Dia": "DATE",
        "Dia_semana": "DAY_OF_WEEK",
        "laborable / festivo / domingo festivo": "DAY_TYPE_RAW",
        "Tipo de Festivo": "HOLIDAY_TYPE",
        "Festividad": "HOLIDAY_NAME"
    },
    inplace=True
)

# Translate weekday names
weekday_map = {
    "lunes": "Monday",
    "martes": "Tuesday",
    "miercoles": "Wednesday",
    "miércoles": "Wednesday",
    "jueves": "Thursday",
    "viernes": "Friday",
    "sabado": "Saturday",
    "sábado": "Saturday",
    "domingo": "Sunday"
}

calendar["DAY_OF_WEEK"] = (
    calendar["DAY_OF_WEEK"]
    .str.lower()
    .map(weekday_map)
)

# Convert raw day type to clean English day type
daytype_map = {
    "laborable": "Weekday",
    "sabado": "Weekend",
    "sábado": "Weekend",
    "domingo": "Weekend",
    "festivo": "Holiday"
}

calendar["DAY_TYPE"] = (
    calendar["DAY_TYPE_RAW"]
    .str.lower()
    .map(daytype_map)
)

# Convert calendar date
calendar["DATE"] = pd.to_datetime(
    calendar["DATE"],
    format="%d/%m/%Y"
)

#only useful calendar columns
calendar = calendar[
    [
        "DATE",
        "DAY_OF_WEEK",
        "DAY_TYPE",
    ]
]

# Create DATE in weather file from YEAR, MONTH, DAY
weather["DATE"] = pd.to_datetime(
    dict(
        year=weather["YEAR"],
        month=weather["MONTH"],
        day=weather["DAY"]
    )
)

# Merge calendar info into weather file
weather = weather.merge(
    calendar,
    on="DATE",
    how="left"
)

# Move DATE and calendar columns near DAY
cols = weather.columns.tolist()

for col in ["DATE", "DAY_OF_WEEK", "DAY_TYPE"]:
    cols.remove(col)

day_index = cols.index("DAY")

cols[day_index + 1:day_index + 1] = [
    "DATE",
    "DAY_OF_WEEK",
    "DAY_TYPE"
]

weather = weather[cols]

# Save final file
weather.to_csv(
    "madrid_weather_2023_2026_with_stationLocation_calendar.csv",
    index=False
)

print("Saved successfully")
print(weather.shape)

print(
    weather.head(20)
)

Saved successfully
(111149, 66)
    PROVINCE  MUNICIPALITY  STATION  MAGNITUDE MAGNITUDE_NAME  SAMPLING_POINT  \
0         28            79      108         81     WIND SPEED  28079108_81_98
1         28            79      108         81     WIND SPEED  28079108_81_98
2         28            79      108         81     WIND SPEED  28079108_81_98
3         28            79      108         81     WIND SPEED  28079108_81_98
4         28            79      108         81     WIND SPEED  28079108_81_98
5         28            79      108         81     WIND SPEED  28079108_81_98
6         28            79      108         81     WIND SPEED  28079108_81_98
7         28            79      108         81     WIND SPEED  28079108_81_98
8         28            79      108         81     WIND SPEED  28079108_81_98
9         28            79      108         81     WIND SPEED  28079108_81_98
10        28            79      108         81     WIND SPEED  28079108_81_98
11        28            79      108         81     WIND SPEED  28079108_81_98
12        28            79      108         81     WIND SPEED  28079108_81_98
13        28            79      108         81     WIND SPEED  28079108_81_98
14        28            79      108         81     WIND SPEED  28079108_81_98
15        28            79      108         81     WIND SPEED  28079108_81_98
16        28            79      108         81     WIND SPEED  28079108_81_98
17        28            79      108         81     WIND SPEED  28079108_81_98
18        28            79      108         81     WIND SPEED  28079108_81_98
19        28            79      108         81     WIND SPEED  28079108_81_98

    YEAR  MONTH  DAY       DATE  ... HOUR_23 VALIDITY_23  HOUR_24 VALIDITY_24  \
0   2023      1    1 2023-01-01  ...    0.30           V     0.40           V
1   2023      1    2 2023-01-02  ...    0.20           V     0.37           V
2   2023      1    3 2023-01-03  ...    0.02           V     0.13           V
3   2023      1    4 2023-01-04  ...    0.00           V     0.10           V
4   2023      1    5 2023-01-05  ...    0.10           V     0.35           V
5   2023      1    6 2023-01-06  ...    0.33           V     0.25           V
6   2023      1    7 2023-01-07  ...    0.23           V     0.40           V
7   2023      1    8 2023-01-08  ...    1.12           V     0.90           V
8   2023      1    9 2023-01-09  ...    0.28           V     0.32           V
9   2023      1   10 2023-01-10  ...    0.55           V     0.37           V
10  2023      1   11 2023-01-11  ...    0.45           V     0.28           V
11  2023      1   12 2023-01-12  ...    0.37           V     0.37           V
12  2023      1   13 2023-01-13  ...    0.25           V     0.18           V
13  2023      1   14 2023-01-14  ...    0.32           V     0.47           V
14  2023      1   15 2023-01-15  ...    1.52           V     1.42           V
15  2023      1   16 2023-01-16  ...    3.03           V     3.40           V
16  2023      1   17 2023-01-17  ...    1.77           V     1.98           V
17  2023      1   18 2023-01-18  ...    1.13           V     1.68           V
18  2023      1   19 2023-01-19  ...    1.72           V     2.45           V
19  2023      1   20 2023-01-20  ...    0.28           V     0.35           V

    source_file STATION_CODE  STATION_NAME ALTITUDE  LONGITUDE   LATITUDE
0   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
1   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
2   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
3   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
4   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
5   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
6   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
7   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
8   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
9   2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
10  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
11  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
12  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
13  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
14  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
15  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
16  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
17  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
18  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944
19  2023_01.csv     28079108    Peñagrande      659  -3.717237  40.476944

[20 rows x 66 columns]

In [33]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

weather.head()

,PROVINCE,MUNICIPALITY,STATION,MAGNITUDE,MAGNITUDE_NAME,SAMPLING_POINT,YEAR,MONTH,DAY,DATE,DAY_OF_WEEK,DAY_TYPE,HOUR_01,VALIDITY_01,HOUR_02,VALIDITY_02,HOUR_03,VALIDITY_03,HOUR_04,VALIDITY_04,HOUR_05,VALIDITY_05,HOUR_06,VALIDITY_06,HOUR_07,VALIDITY_07,HOUR_08,VALIDITY_08,HOUR_09,VALIDITY_09,HOUR_10,VALIDITY_10,HOUR_11,VALIDITY_11,HOUR_12,VALIDITY_12,HOUR_13,VALIDITY_13,HOUR_14,VALIDITY_14,HOUR_15,VALIDITY_15,HOUR_16,VALIDITY_16,HOUR_17,VALIDITY_17,HOUR_18,VALIDITY_18,HOUR_19,VALIDITY_19,HOUR_20,VALIDITY_20,HOUR_21,VALIDITY_21,HOUR_22,VALIDITY_22,HOUR_23,VALIDITY_23,HOUR_24,VALIDITY_24,source_file,STATION_CODE,STATION_NAME,ALTITUDE,LONGITUDE,LATITUDE
0,28,79,108,81,WIND SPEED,28079108_81_98,2023,1,1,2023-01-01,Sunday,Weekend,0.67,V,1.10,V,0.98,V,1.00,V,0.82,V,0.68,V,0.70,V,0.55,V,1.07,V,0.65,V,0.85,V,0.72,V,1.07,V,0.82,V,0.95,V,0.50,V,0.52,V,0.23,V,0.47,V,0.72,V,0.57,V,0.35,V,0.30,V,0.40,V,2023_01.csv,28079108,Peñagrande,659,-3.717237,40.476944
1,28,79,108,81,WIND SPEED,28079108_81_98,2023,1,2,2023-01-02,Monday,Weekday,0.77,V,0.72,V,0.57,V,0.33,V,0.33,V,0.32,V,0.28,V,0.20,V,0.25,V,0.40,V,0.50,V,0.65,V,1.57,V,1.00,V,0.65,V,0.78,V,0.80,V,0.40,V,0.35,V,0.22,V,0.13,V,0.30,V,0.20,V,0.37,V,2023_01.csv,28079108,Peñagrande,659,-3.717237,40.476944
2,28,79,108,81,WIND SPEED,28079108_81_98,2023,1,3,2023-01-03,Tuesday,Weekday,0.30,V,0.50,V,0.45,V,0.17,V,0.68,V,0.38,V,0.33,V,0.40,V,0.37,V,0.08,V,0.62,V,1.13,V,1.12,V,0.88,V,0.85,V,0.55,V,0.60,V,0.38,V,0.17,V,0.10,V,0.10,V,0.18,V,0.02,V,0.13,V,2023_01.csv,28079108,Peñagrande,659,-3.717237,40.476944
3,28,79,108,81,WIND SPEED,28079108_81_98,2023,1,4,2023-01-04,Wednesday,Weekday,0.50,V,0.33,V,0.45,V,0.25,V,0.12,V,0.18,V,0.03,V,0.25,V,0.13,V,0.25,V,0.67,V,0.90,V,0.60,V,0.53,V,0.67,V,0.80,V,0.72,V,0.25,V,0.17,V,0.03,V,0.08,V,0.10,V,0.00,V,0.10,V,2023_01.csv,28079108,Peñagrande,659,-3.717237,40.476944
4,28,79,108,81,WIND SPEED,28079108_81_98,2023,1,5,2023-01-05,Thursday,Weekday,0.18,V,0.28,V,0.20,V,0.25,V,0.10,V,0.18,V,0.40,V,0.15,V,0.18,V,0.52,V,1.00,V,1.28,V,0.80,V,0.58,V,0.92,V,0.93,V,0.87,V,0.35,V,0.17,V,0.22,V,0.02,V,0.02,V,0.10,V,0.35,V,2023_01.csv,28079108,Peñagrande,659,-3.717237,40.476944

In [35]:
weather.drop(
    columns=[
        "PROVINCE",
        "MUNICIPALITY"
    ],
    inplace=True
)
weather.to_csv(
    "madrid_weather_final.csv",
    index=False
)

In [37]:
import os
import re
import time
import zipfile
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from pathlib import Path
from io import BytesIO

BASE = "https://datos.madrid.es/dataset/208627-0-transporte-ptomedida-historico/downloads"

START_YEAR = 2023
END_YEAR = 2026

month_map = {
    "Enero": "01",
    "Febrero": "02",
    "Marzo": "03",
    "Abril": "04",
    "Mayo": "05",
    "Junio": "06",
    "Julio": "07",
    "Agosto": "08",
    "Septiembre": "09",
    "Octubre": "10",
    "Noviembre": "11",
    "Diciembre": "12"
}

def get_with_retries(url, retries=5, sleep_seconds=10):
    for attempt in range(1, retries + 1):
        try:
            r = requests.get(url, timeout=180)
            r.raise_for_status()
            return r
        except requests.exceptions.RequestException as e:
            print(f"Attempt {attempt} failed:")
            print(e)

            if attempt == retries:
                raise

            print(f"Waiting {sleep_seconds} seconds before retry...")
            time.sleep(sleep_seconds)

html = get_with_retries(BASE).text
soup = BeautifulSoup(html, "html.parser")

resources = []

for a in soup.find_all("a", href=True):
    text = " ".join(a.get_text(" ", strip=True).split())
    href = urljoin(BASE, a["href"])

    match = re.search(
        r"ZIP Histórico de datos del tráfico\. (\w+) (\d{4})",
        text
    )

    if match and href.endswith("-zip"):
        month_name = match.group(1)
        year = int(match.group(2))

        if START_YEAR <= year <= END_YEAR:
            month_num = month_map.get(month_name)

            if month_num:
                resource_id = href.rstrip("/").split("/")[-1]
                download_url = f"{href}/download/{resource_id}"

                resources.append({
                    "year": year,
                    "month": month_num,
                    "title": text,
                    "url": download_url
                })

resources = sorted(resources, key=lambda x: (x["year"], x["month"]))

print(f"Found {len(resources)} ZIP files")

failed = []

for item in resources:
    year = item["year"]
    month = item["month"]

    out_dir = Path(f"madrid_traffic_{year}_csv")
    out_dir.mkdir(exist_ok=True)

    output_path = out_dir / f"{year}_{month}_traffic.csv"

    # Resume feature: skip if file already exists
    if output_path.exists() and output_path.stat().st_size > 0:
        print(f"Already exists, skipping: {output_path}")
        continue

    print(f"Downloading {year}-{month}: {item['title']}")

    try:
        response = get_with_retries(item["url"], retries=5, sleep_seconds=15)

        with zipfile.ZipFile(BytesIO(response.content)) as z:
            csv_files = [
                name for name in z.namelist()
                if name.lower().endswith(".csv")
            ]

            if not csv_files:
                print(f"No CSV found inside ZIP for {year}-{month}")
                failed.append(item)
                continue

            csv_name = csv_files[0]

            with z.open(csv_name) as source, open(output_path, "wb") as target:
                target.write(source.read())

            print(f"Saved: {output_path}")

        time.sleep(2)

    except Exception as e:
        print(f"Failed permanently for {year}-{month}")
        print(e)
        failed.append(item)

print("Done.")

if failed:
    print("\nFailed files:")
    for item in failed:
        print(item["year"], item["month"], item["url"])
else:
    print("All files downloaded successfully.")

Found 36 ZIP files
Already exists, skipping: madrid_traffic_2023_csv/2023_01_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_02_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_03_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_04_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_05_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_06_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_07_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_08_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_09_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_10_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_11_traffic.csv
Already exists, skipping: madrid_traffic_2023_csv/2023_12_traffic.csv
Downloading 2024-01: ZIP Histórico de datos del tráfico. Enero 2024 Descargado 976 veces. Tamaño: 80.8 MB
Saved: madrid_traffic_2024_csv/2024_01_traffic.csv
Downloading 2024-02: ZIP Histórico de datos del tráfico. Febrero 2024 Descargado 1.228 veces. Tamaño: 76.2 MB
Saved: madrid_traffic_2024_csv/2024_02_traffic.csv
Downloading 2024-03: ZIP Histórico de datos del tráfico. Marzo 2024 Descargado 874 veces. Tamaño: 81.2 MB
Saved: madrid_traffic_2024_csv/2024_03_traffic.csv
Downloading 2024-04: ZIP Histórico de datos del tráfico. Abril 2024 Descargado 869 veces. Tamaño: 79.4 MB
Saved: madrid_traffic_2024_csv/2024_04_traffic.csv
Downloading 2024-05: ZIP Histórico de datos del tráfico. Mayo 2024 Descargado 968 veces. Tamaño: 81.5 MB
Saved: madrid_traffic_2024_csv/2024_05_traffic.csv
Downloading 2024-06: ZIP Histórico de datos del tráfico. Junio 2024 Descargado 857 veces. Tamaño: 78.7 MB
Saved: madrid_traffic_2024_csv/2024_06_traffic.csv
Downloading 2024-07: ZIP Histórico de datos del tráfico. Julio 2024 Descargado 846 veces. Tamaño: 79.9 MB
Attempt 1 failed:
HTTPSConnectionPool(host='datos.madrid.es', port=443): Max retries exceeded with url: /dataset/208627-0-transporte-ptomedida-historico/resource/208627-36-transporte-ptomedida-historico-zip/download/208627-36-transporte-ptomedida-historico-zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1164b1e50>: Failed to resolve 'datos.madrid.es' ([Errno 8] nodename nor servname provided, or not known)"))
Waiting 15 seconds before retry...
Saved: madrid_traffic_2024_csv/2024_07_traffic.csv
Downloading 2024-08: ZIP Histórico de datos del tráfico. Agosto 2024 Descargado 982 veces. Tamaño: 76.6 MB
Saved: madrid_traffic_2024_csv/2024_08_traffic.csv
Downloading 2024-09: ZIP Histórico de datos del tráfico. Septiembre 2024 Descargado 886 veces. Tamaño: 77.3 MB
Saved: madrid_traffic_2024_csv/2024_09_traffic.csv
Downloading 2024-10: ZIP Histórico de datos del tráfico. Octubre 2024 Descargado 923 veces. Tamaño: 87.8 MB
Saved: madrid_traffic_2024_csv/2024_10_traffic.csv
Downloading 2024-11: ZIP Histórico de datos del tráfico. Noviembre 2024 Descargado 769 veces. Tamaño: 84.7 MB
Saved: madrid_traffic_2024_csv/2024_11_traffic.csv
Downloading 2024-12: ZIP Histórico de datos del tráfico. Diciembre 2024 Descargado 898 veces. Tamaño: 89.4 MB
Saved: madrid_traffic_2024_csv/2024_12_traffic.csv
Downloading 2025-01: ZIP Histórico de datos del tráfico. Enero 2025 Descargado 847 veces. Tamaño: 88.9 MB
Saved: madrid_traffic_2025_csv/2025_01_traffic.csv
Downloading 2025-02: ZIP Histórico de datos del tráfico. Febrero 2025 Descargado 749 veces. Tamaño: 81.1 MB
Saved: madrid_traffic_2025_csv/2025_02_traffic.csv
Downloading 2025-03: ZIP Histórico de datos del tráfico. Marzo 2025 Descargado 824 veces. Tamaño: 89.5 MB
Saved: madrid_traffic_2025_csv/2025_03_traffic.csv
Downloading 2025-04: ZIP Histórico de datos del tráfico. Abril 2025 Descargado 720 veces. Tamaño: 80.8 MB
Saved: madrid_traffic_2025_csv/2025_04_traffic.csv
Downloading 2025-05: ZIP Histórico de datos del tráfico. Mayo 2025 Descargado 709 veces. Tamaño: 90.3 MB
Saved: madrid_traffic_2025_csv/2025_05_traffic.csv
Downloading 2025-06: ZIP Histórico de datos del tráfico. Junio 2025 Descargado 791 veces. Tamaño: 87.4 MB
Saved: madrid_traffic_2025_csv/2025_06_traffic.csv
Downloading 2025-07: ZIP Histórico de datos del tráfico. Julio 2025 Descargado 662 veces. Tamaño: 90.0 MB
Saved: madrid_traffic_2025_csv/2025_07_traffic.csv
Downloading 2025-08: ZIP Histórico de datos del tráfico. Agosto 2025 Descargado 570 veces. Tamaño: 86.3 MB
Saved: madrid_traffic_2025_csv/2025_08_traffic.csv
Downloading 2025-09: ZIP Histórico de datos del tráfico. Septiembre 2025 Descargado 627 veces. Tamaño: 87.7 MB
Saved: madrid_traffic_2025_csv/2025_09_traffic.csv
Downloading 2025-10: ZIP Histórico de datos del tráfico. Octubre 2025 Descargado 665 veces. Tamaño: 91.8 MB
Saved: madrid_traffic_2025_csv/2025_10_traffic.csv
Downloading 2025-11: ZIP Histórico de datos del tráfico. Noviembre 2025 Descargado 603 veces. Tamaño: 88.2 MB
Saved: madrid_traffic_2025_csv/2025_11_traffic.csv
Downloading 2025-12: ZIP Histórico de datos del tráfico. Diciembre 2025 Descargado 630 veces. Tamaño: 90.1 MB
Saved: madrid_traffic_2025_csv/2025_12_traffic.csv
Done.
All files downloaded successfully.

In [39]:
import time
import zipfile
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
from pathlib import Path
from io import BytesIO

BASE = "https://datos.madrid.es/dataset/208627-0-transporte-ptomedida-historico/downloads"
YEAR = 2026

month_map = {
    "Enero": "01",
    "Febrero": "02",
    "Marzo": "03",
    "Abril": "04",
    "Mayo": "05",
    "Junio": "06",
    "Julio": "07",
    "Agosto": "08",
    "Septiembre": "09",
    "Octubre": "10",
    "Noviembre": "11",
    "Diciembre": "12"
}

def get_with_retries(url, retries=5):
    for attempt in range(1, retries + 1):
        try:
            r = requests.get(url, timeout=180)
            r.raise_for_status()
            return r
        except requests.exceptions.RequestException as e:
            print(f"Attempt {attempt} failed: {e}")
            time.sleep(10)
    raise Exception(f"Failed after {retries} retries: {url}")

html = get_with_retries(BASE).text
soup = BeautifulSoup(html, "html.parser")

resources = []

for a in soup.find_all("a", href=True):
    text = " ".join(a.get_text(" ", strip=True).split())
    href = urljoin(BASE, a["href"])

    if "Histórico de datos del tráfico" in text and str(YEAR) in text:
        for month_name, month_num in month_map.items():
            if month_name in text:
                resource_id = href.rstrip("/").split("/")[-1]
                download_url = f"{href}/download/{resource_id}.zip"

                resources.append({
                    "month": month_num,
                    "title": text,
                    "url": download_url
                })

resources = sorted(resources, key=lambda x: x["month"])

print(f"Found {len(resources)} files for {YEAR}")
for r in resources:
    print(r["month"], r["title"])
    print(r["url"])

out_dir = Path(f"madrid_traffic_{YEAR}_csv")
out_dir.mkdir(exist_ok=True)

for item in resources:
    output_path = out_dir / f"{YEAR}_{item['month']}_traffic.csv"

    if output_path.exists() and output_path.stat().st_size > 0:
        print(f"Already exists, skipping: {output_path}")
        continue

    print(f"Downloading {YEAR}-{item['month']}")

    response = get_with_retries(item["url"])

    with zipfile.ZipFile(BytesIO(response.content)) as z:
        csv_files = [
            name for name in z.namelist()
            if name.lower().endswith(".csv")
        ]

        if not csv_files:
            print("No CSV found:", item["title"])
            continue

        with z.open(csv_files[0]) as source, open(output_path, "wb") as target:
            target.write(source.read())

    print(f"Saved: {output_path}")

print("Done.")

Attempt 1 failed: HTTPSConnectionPool(host='datos.madrid.es', port=443): Max retries exceeded with url: /dataset/208627-0-transporte-ptomedida-historico/downloads (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1166e7c50>: Failed to resolve 'datos.madrid.es' ([Errno 8] nodename nor servname provided, or not known)"))
Found 5 files for 2026
01 ZIP Histórico de datos del tráfico. Enero 2026 Descargado 252 veces. Tamaño: 82.3 MB
https://datos.madrid.es/dataset/208627-0-transporte-ptomedida-historico/resource/208627-153-transporte-ptomedida-historico/download/208627-153-transporte-ptomedida-historico.zip
02 ZIP Histórico de datos del tráfico. Febrero 2026 Descargado 282 veces. Tamaño: 79.4 MB
https://datos.madrid.es/dataset/208627-0-transporte-ptomedida-historico/resource/208627-154-transporte-ptomedida-historico/download/208627-154-transporte-ptomedida-historico.zip
03 ZIP Histórico de datos del tráfico. Marzo 2026 Descargado 214 veces. Tamaño: 89.4 MB
https://datos.madrid.es/dataset/208627-0-transporte-ptomedida-historico/resource/208627-155-transporte-ptomedida-historico/download/208627-155-transporte-ptomedida-historico.zip
04 ZIP Histórico de datos del tráfico. Abril 2026 Descargado 135 veces. Tamaño: 89.2 MB
https://datos.madrid.es/dataset/208627-0-transporte-ptomedida-historico/resource/208627-156-transporte-ptomedida-historico/download/208627-156-transporte-ptomedida-historico.zip
05 ZIP Histórico de datos del tráfico. Mayo 2026 Descargado 10 veces. Tamaño: 92.7 MB
https://datos.madrid.es/dataset/208627-0-transporte-ptomedida-historico/resource/208627-157-transporte-ptomedida-historico/download/208627-157-transporte-ptomedida-historico.zip
Downloading 2026-01
Saved: madrid_traffic_2026_csv/2026_01_traffic.csv
Downloading 2026-02
Saved: madrid_traffic_2026_csv/2026_02_traffic.csv
Downloading 2026-03
Saved: madrid_traffic_2026_csv/2026_03_traffic.csv
Downloading 2026-04
Saved: madrid_traffic_2026_csv/2026_04_traffic.csv
Downloading 2026-05
Saved: madrid_traffic_2026_csv/2026_05_traffic.csv
Done.

In [41]:
import pandas as pd
from pathlib import Path

folders = [
    "madrid_traffic_2023_csv",
    "madrid_traffic_2024_csv",
    "madrid_traffic_2025_csv",
    "madrid_traffic_2026_csv"
]

files = []

for folder in folders:
    files.extend(sorted(Path(folder).glob("*.csv")))

print(f"Total files found: {len(files)}")

columns_by_file = {}

for file in files:
    df_head = pd.read_csv(file, sep=";", nrows=0, low_memory=False)
    columns_by_file[file.name] = list(df_head.columns)

# Use first file as reference
reference_file = files[0].name
reference_columns = columns_by_file[reference_file]

print("Reference file:", reference_file)
print("Reference columns:")
print(reference_columns)

print("\nChecking column consistency...\n")

all_same = True

for file_name, cols in columns_by_file.items():
    if cols != reference_columns:
        all_same = False
        print(f"Different columns found in: {file_name}")
        print("Missing compared to reference:")
        print(set(reference_columns) - set(cols))
        print("Extra compared to reference:")
        print(set(cols) - set(reference_columns))
        print("-" * 60)

if all_same:
    print("All files have exactly the same columns.")
else:
    print("Some files have different columns.")

for file_name, cols in columns_by_file.items():
    print("\n", file_name)
    print(cols)

for file in files:
    df_temp = pd.read_csv(file, sep=";", low_memory=False)
    print(file.name, df_temp.shape)

Total files found: 41
Reference file: 2023_01_traffic.csv
Reference columns:
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

Checking column consistency...

All files have exactly the same columns.

 2023_01_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_02_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_03_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_04_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_05_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_06_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_07_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_08_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_09_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_10_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_11_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2023_12_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_01_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_02_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_03_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_04_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_05_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_06_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_07_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_08_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_09_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_10_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_11_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2024_12_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_01_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_02_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_03_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_04_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_05_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_06_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_07_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_08_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_09_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_10_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_11_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2025_12_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2026_01_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2026_02_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2026_03_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2026_04_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']

 2026_05_traffic.csv
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']
2023_01_traffic.csv (12644350, 9)
2023_02_traffic.csv (11388974, 9)
2023_03_traffic.csv (12732652, 9)
2023_04_traffic.csv (12438772, 9)
2023_05_traffic.csv (12926315, 9)
2023_06_traffic.csv (12485567, 9)
2023_07_traffic.csv (12945236, 9)
2023_08_traffic.csv (12744711, 9)
2023_09_traffic.csv (12518185, 9)
2023_10_traffic.csv (12946685, 9)
2023_11_traffic.csv (12774666, 9)
2023_12_traffic.csv (13224732, 9)
2024_01_traffic.csv (13343452, 9)
2024_02_traffic.csv (12532935, 9)
2024_03_traffic.csv (13451928, 9)
2024_04_traffic.csv (13010780, 9)
2024_05_traffic.csv (13357035, 9)
2024_06_traffic.csv (12918338, 9)
2024_07_traffic.csv (13351339, 9)
2024_08_traffic.csv (13214710, 9)
2024_09_traffic.csv (12779019, 9)
2024_10_traffic.csv (12918900, 9)
2024_11_traffic.csv (12513169, 9)
2024_12_traffic.csv (13296461, 9)
2025_01_traffic.csv (13218804, 9)
2025_02_traffic.csv (12056165, 9)
2025_03_traffic.csv (13332490, 9)
2025_04_traffic.csv (12122708, 9)
2025_05_traffic.csv (13506878, 9)
2025_06_traffic.csv (13004398, 9)
2025_07_traffic.csv (13571079, 9)
2025_08_traffic.csv (13451998, 9)
2025_09_traffic.csv (13082675, 9)
2025_10_traffic.csv (13591523, 9)
2025_11_traffic.csv (13094538, 9)
2025_12_traffic.csv (13459494, 9)
2026_01_traffic.csv (14296853, 9)
2026_02_traffic.csv (11948889, 9)
2026_03_traffic.csv (13494039, 9)
2026_04_traffic.csv (13389478, 9)
2026_05_traffic.csv (13775364, 9)

In [42]:
import pandas as pd

df = pd.read_csv(
    "madrid_traffic_2023_csv/2023_01_traffic.csv",
    sep=";",
    low_memory=False
)

print(df.shape)
print(df.columns.tolist())

pd.set_option('display.max_columns', None)

print(df.head())
print(df.info())

(12644350, 9)
['id', 'fecha', 'tipo_elem', 'intensidad', 'ocupacion', 'carga', 'vmed', 'error', 'periodo_integracion']
     id                fecha tipo_elem  intensidad  ocupacion  carga  vmed  \
0  1001  2023-01-01 00:00:00       C30           0        0.0      0   0.0
1  1001  2023-01-01 00:15:00       C30           0        0.0      0   0.0
2  1001  2023-01-01 00:30:00       C30         180        0.0      0  66.0
3  1001  2023-01-01 00:45:00       C30         180        0.0      0  66.0
4  1001  2023-01-01 01:00:00       C30         180        0.0      0  66.0

  error  periodo_integracion
0     N                    5
1     N                    5
2     N                    5
3     N                    5
4     N                    5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12644350 entries, 0 to 12644349
Data columns (total 9 columns):
 #   Column               Dtype
---  ------               -----
 0   id                   int64
 1   fecha                object
 2   tipo_elem            object
 3   intensidad           int64
 4   ocupacion            float64
 5   carga                int64
 6   vmed                 float64
 7   error                object
 8   periodo_integracion  int64
dtypes: float64(2), int64(4), object(3)
memory usage: 868.2+ MB
None

In [1]:
import pandas as pd
from pathlib import Path

folders = [
    "madrid_traffic_2023_csv",
    "madrid_traffic_2024_csv",
    "madrid_traffic_2025_csv",
    "madrid_traffic_2026_csv"
]

column_mapping = {
    "id": "SENSOR_ID",
    "fecha": "DATETIME",
    "tipo_elem": "ELEMENT_TYPE",
    "intensidad": "TRAFFIC_INTENSITY",
    "ocupacion": "OCCUPANCY",
    "carga": "LOAD",
    "vmed": "AVERAGE_SPEED",
    "error": "ERROR_FLAG",
    "periodo_integracion": "INTEGRATION_PERIOD"
}

files = []
for folder in folders:
    files.extend(sorted(Path(folder).glob("*.csv")))

print(f"Found {len(files)} files")

dfs = []

for file in files:
    print(f"Reading {file}")

    df = pd.read_csv(
        file,
        sep=";",
        low_memory=False
    )

    df.rename(columns=column_mapping, inplace=True)

    dfs.append(df)

traffic = pd.concat(dfs, ignore_index=True)

traffic.to_csv(
    "madrid_traffic_2023_2026.csv",
    index=False
)

print("Saved successfully")
print(traffic.shape)
print(traffic.head())

Found 41 files
Reading madrid_traffic_2023_csv/2023_01_traffic.csv
Reading madrid_traffic_2023_csv/2023_02_traffic.csv
Reading madrid_traffic_2023_csv/2023_03_traffic.csv
Reading madrid_traffic_2023_csv/2023_04_traffic.csv
Reading madrid_traffic_2023_csv/2023_05_traffic.csv
Reading madrid_traffic_2023_csv/2023_06_traffic.csv
Reading madrid_traffic_2023_csv/2023_07_traffic.csv
Reading madrid_traffic_2023_csv/2023_08_traffic.csv
Reading madrid_traffic_2023_csv/2023_09_traffic.csv
Reading madrid_traffic_2023_csv/2023_10_traffic.csv
Reading madrid_traffic_2023_csv/2023_11_traffic.csv
Reading madrid_traffic_2023_csv/2023_12_traffic.csv
Reading madrid_traffic_2024_csv/2024_01_traffic.csv
Reading madrid_traffic_2024_csv/2024_02_traffic.csv
Reading madrid_traffic_2024_csv/2024_03_traffic.csv
Reading madrid_traffic_2024_csv/2024_04_traffic.csv
Reading madrid_traffic_2024_csv/2024_05_traffic.csv
Reading madrid_traffic_2024_csv/2024_06_traffic.csv
Reading madrid_traffic_2024_csv/2024_07_traffic.csv
Reading madrid_traffic_2024_csv/2024_08_traffic.csv
Reading madrid_traffic_2024_csv/2024_09_traffic.csv
Reading madrid_traffic_2024_csv/2024_10_traffic.csv
Reading madrid_traffic_2024_csv/2024_11_traffic.csv
Reading madrid_traffic_2024_csv/2024_12_traffic.csv
Reading madrid_traffic_2025_csv/2025_01_traffic.csv
Reading madrid_traffic_2025_csv/2025_02_traffic.csv
Reading madrid_traffic_2025_csv/2025_03_traffic.csv
Reading madrid_traffic_2025_csv/2025_04_traffic.csv
Reading madrid_traffic_2025_csv/2025_05_traffic.csv
Reading madrid_traffic_2025_csv/2025_06_traffic.csv
Reading madrid_traffic_2025_csv/2025_07_traffic.csv
Reading madrid_traffic_2025_csv/2025_08_traffic.csv
Reading madrid_traffic_2025_csv/2025_09_traffic.csv
Reading madrid_traffic_2025_csv/2025_10_traffic.csv
Reading madrid_traffic_2025_csv/2025_11_traffic.csv
Reading madrid_traffic_2025_csv/2025_12_traffic.csv
Reading madrid_traffic_2026_csv/2026_01_traffic.csv
Reading madrid_traffic_2026_csv/2026_02_traffic.csv
Reading madrid_traffic_2026_csv/2026_03_traffic.csv
Reading madrid_traffic_2026_csv/2026_04_traffic.csv
Reading madrid_traffic_2026_csv/2026_05_traffic.csv
Saved successfully
(532856284, 9)
   SENSOR_ID             DATETIME ELEMENT_TYPE  TRAFFIC_INTENSITY  OCCUPANCY  \
0       1001  2023-01-01 00:00:00          C30                  0        0.0
1       1001  2023-01-01 00:15:00          C30                  0        0.0
2       1001  2023-01-01 00:30:00          C30                180        0.0
3       1001  2023-01-01 00:45:00          C30                180        0.0
4       1001  2023-01-01 01:00:00          C30                180        0.0

   LOAD  AVERAGE_SPEED ERROR_FLAG  INTEGRATION_PERIOD
0     0            0.0          N                   5
1     0            0.0          N                   5
2     0           66.0          N                   5
3     0           66.0          N                   5
4     0           66.0          N                   5

In [2]:
print(traffic.columns.tolist())

['SENSOR_ID', 'DATETIME', 'ELEMENT_TYPE', 'TRAFFIC_INTENSITY', 'OCCUPANCY', 'LOAD', 'AVERAGE_SPEED', 'ERROR_FLAG', 'INTEGRATION_PERIOD']

In [4]:
import pandas as pd

locations = pd.read_csv(
    "TrafficSensorLocations.csv",
    sep=";",
    encoding="latin-1",
    low_memory=False
)

print(locations.shape)
print(locations.columns.tolist())
print(locations.head().to_string())

(5072, 9)
['tipo_elem', 'distrito', 'id', 'cod_cent', 'nombre', 'utm_x', 'utm_y', 'longitud', 'latitud']
  tipo_elem  distrito    id    cod_cent                                          nombre          utm_x         utm_y  longitud    latitud
0     other       1.0  6835  18RA28PM01                                      18RA28PM01  438764.313318  4.474327e+06 -3.721794  40.417315
1     other       9.0  1012  18RA66PM01                                      18RA66PM01  438740.943152  4.474610e+06 -3.722097  40.419861
2       URB      10.0  5035       95013                                      FRUELA N-S  438004.401612  4.473859e+06 -3.730705  40.413040
3       URB       5.0  5579       61068     Potosi E-O - Bolivia-Víctor Andrés Belaunde  442420.642251  4.478696e+06 -3.679095  40.456932
4       URB       5.0  5580       61069  Víctor Andrés Belaunde N-S - Cochabamba-Potosi  442366.670466  4.478601e+06 -3.679723  40.456073

In [ ]:
%%memit
import pandas as pd

traffic = pd.read_csv(
    "madrid_traffic_2023_2026.csv",
    low_memory=False
)

locations = pd.read_csv(
    "TrafficSensorLocations.csv",
    sep=";",
    encoding="latin-1",
    low_memory=False
)

locations_small = locations[
    ["id", "longitud", "latitud"]
].copy()

locations_small.rename(
    columns={
        "id": "SENSOR_ID",
        "longitud": "LONGITUDE",
        "latitud": "LATITUDE"
    },
    inplace=True
)

traffic = traffic.merge(
    locations_small,
    on="SENSOR_ID",
    how="left"
)

traffic.to_csv(
    "madrid_traffic_2023_2026_with_location.csv",
    index=False
)

print("Saved successfully")
print(traffic.shape)

print(
    traffic[
        ["SENSOR_ID", "DATETIME", "LONGITUDE", "LATITUDE"]
    ].head()
)
print("Rows without location:", traffic["LATITUDE"].isna().sum())

In [1]:
import pandas as pd

weather = pd.read_csv(
    "madrid_weather_final.csv",
    low_memory=False
)

In [2]:
weather["MAGNITUDE_NAME"].value_counts()

MAGNITUDE_NAME
TEMPERATURE            29471
RELATIVE HUMIDITY      26925
PRECIPITATION          11970
WIND SPEED             11869
WIND DIRECTION         11869
SOLAR RADIATION         9542
BAROMETRIC PRESSURE     9503
Name: count, dtype: int64

In [3]:
weather["STATION_CODE"].nunique()

26

In [4]:
print(weather.columns.tolist())

['STATION', 'MAGNITUDE', 'MAGNITUDE_NAME', 'SAMPLING_POINT', 'YEAR', 'MONTH', 'DAY', 'DATE', 'DAY_OF_WEEK', 'DAY_TYPE', 'HOUR_01', 'VALIDITY_01', 'HOUR_02', 'VALIDITY_02', 'HOUR_03', 'VALIDITY_03', 'HOUR_04', 'VALIDITY_04', 'HOUR_05', 'VALIDITY_05', 'HOUR_06', 'VALIDITY_06', 'HOUR_07', 'VALIDITY_07', 'HOUR_08', 'VALIDITY_08', 'HOUR_09', 'VALIDITY_09', 'HOUR_10', 'VALIDITY_10', 'HOUR_11', 'VALIDITY_11', 'HOUR_12', 'VALIDITY_12', 'HOUR_13', 'VALIDITY_13', 'HOUR_14', 'VALIDITY_14', 'HOUR_15', 'VALIDITY_15', 'HOUR_16', 'VALIDITY_16', 'HOUR_17', 'VALIDITY_17', 'HOUR_18', 'VALIDITY_18', 'HOUR_19', 'VALIDITY_19', 'HOUR_20', 'VALIDITY_20', 'HOUR_21', 'VALIDITY_21', 'HOUR_22', 'VALIDITY_22', 'HOUR_23', 'VALIDITY_23', 'HOUR_24', 'VALIDITY_24', 'source_file', 'STATION_CODE', 'STATION_NAME', 'ALTITUDE', 'LONGITUDE', 'LATITUDE']

In [5]:
print(weather.shape)
print(weather.columns.tolist())

(111149, 64)
['STATION', 'MAGNITUDE', 'MAGNITUDE_NAME', 'SAMPLING_POINT', 'YEAR', 'MONTH', 'DAY', 'DATE', 'DAY_OF_WEEK', 'DAY_TYPE', 'HOUR_01', 'VALIDITY_01', 'HOUR_02', 'VALIDITY_02', 'HOUR_03', 'VALIDITY_03', 'HOUR_04', 'VALIDITY_04', 'HOUR_05', 'VALIDITY_05', 'HOUR_06', 'VALIDITY_06', 'HOUR_07', 'VALIDITY_07', 'HOUR_08', 'VALIDITY_08', 'HOUR_09', 'VALIDITY_09', 'HOUR_10', 'VALIDITY_10', 'HOUR_11', 'VALIDITY_11', 'HOUR_12', 'VALIDITY_12', 'HOUR_13', 'VALIDITY_13', 'HOUR_14', 'VALIDITY_14', 'HOUR_15', 'VALIDITY_15', 'HOUR_16', 'VALIDITY_16', 'HOUR_17', 'VALIDITY_17', 'HOUR_18', 'VALIDITY_18', 'HOUR_19', 'VALIDITY_19', 'HOUR_20', 'VALIDITY_20', 'HOUR_21', 'VALIDITY_21', 'HOUR_22', 'VALIDITY_22', 'HOUR_23', 'VALIDITY_23', 'HOUR_24', 'VALIDITY_24', 'source_file', 'STATION_CODE', 'STATION_NAME', 'ALTITUDE', 'LONGITUDE', 'LATITUDE']

In [6]:
print(type(weather))

<class 'pandas.core.frame.DataFrame'>

In [7]:
hour_cols = [f"HOUR_{i:02d}" for i in range(1, 25)]

test = weather.melt(
    id_vars=[
        "STATION_CODE",
        "STATION_NAME",
        "MAGNITUDE_NAME",
        "DATE",
        "LATITUDE",
        "LONGITUDE",
        "ALTITUDE"
    ],
    value_vars=hour_cols[:2],  # only HOUR_01 and HOUR_02
    var_name="HOUR_COL",
    value_name="WEATHER_VALUE"
)

print(test.shape)
test.head()

(222298, 9)

,STATION_CODE,STATION_NAME,MAGNITUDE_NAME,DATE,LATITUDE,LONGITUDE,ALTITUDE,HOUR_COL,WEATHER_VALUE
0,28079108,Peñagrande,WIND SPEED,2023-01-01,40.476944,-3.717237,659,HOUR_01,0.67
1,28079108,Peñagrande,WIND SPEED,2023-01-02,40.476944,-3.717237,659,HOUR_01,0.77
2,28079108,Peñagrande,WIND SPEED,2023-01-03,40.476944,-3.717237,659,HOUR_01,0.30
3,28079108,Peñagrande,WIND SPEED,2023-01-04,40.476944,-3.717237,659,HOUR_01,0.50
4,28079108,Peñagrande,WIND SPEED,2023-01-05,40.476944,-3.717237,659,HOUR_01,0.18

In [8]:
import pandas as pd
from pathlib import Path

output_path = Path.home() / "Downloads" / "weather_hourly.parquet"

hour_cols = [f"HOUR_{i:02d}" for i in range(1, 25)]
validity_cols = [f"VALIDITY_{i:02d}" for i in range(1, 25)]

id_cols = [
    "STATION_CODE",
    "STATION_NAME",
    "MAGNITUDE_NAME",
    "DATE",
    "LATITUDE",
    "LONGITUDE",
    "ALTITUDE"
]

value_long = weather.melt(
    id_vars=id_cols,
    value_vars=hour_cols,
    var_name="HOUR_COL",
    value_name="WEATHER_VALUE"
)

validity_long = weather.melt(
    id_vars=id_cols,
    value_vars=validity_cols,
    var_name="VALIDITY_COL",
    value_name="VALIDITY"
)

value_long["HOUR_NUM"] = value_long["HOUR_COL"].str.extract(r"(\d+)").astype(int)
validity_long["HOUR_NUM"] = validity_long["VALIDITY_COL"].str.extract(r"(\d+)").astype(int)

weather_long = value_long.merge(
    validity_long[id_cols + ["HOUR_NUM", "VALIDITY"]],
    on=id_cols + ["HOUR_NUM"],
    how="left"
)

weather_long["WEATHER_DATETIME"] = (
    pd.to_datetime(weather_long["DATE"]) +
    pd.to_timedelta(weather_long["HOUR_NUM"] - 1, unit="h")
)

weather_long = weather_long[weather_long["VALIDITY"] == "V"].copy()

weather_long["MAGNITUDE_NAME"] = (
    weather_long["MAGNITUDE_NAME"]
    .str.upper()
    .str.replace(" ", "_", regex=False)
)

weather_hourly = weather_long.pivot_table(
    index=[
        "STATION_CODE",
        "STATION_NAME",
        "WEATHER_DATETIME",
        "LATITUDE",
        "LONGITUDE",
        "ALTITUDE"
    ],
    columns="MAGNITUDE_NAME",
    values="WEATHER_VALUE",
    aggfunc="mean"
).reset_index()

weather_hourly = weather_hourly.rename(columns={
    "LATITUDE": "WEATHER_LATITUDE",
    "LONGITUDE": "WEATHER_LONGITUDE",
    "ALTITUDE": "WEATHER_ALTITUDE"
})

weather_hourly.to_parquet(output_path, index=False)

print("Saved:", output_path)
print(weather_hourly.shape)
print(weather_hourly.columns.tolist())
display(weather_hourly.head())

Saved: /Users/bunny/Downloads/weather_hourly.parquet
(724612, 13)
['STATION_CODE', 'STATION_NAME', 'WEATHER_DATETIME', 'WEATHER_LATITUDE', 'WEATHER_LONGITUDE', 'WEATHER_ALTITUDE', 'BAROMETRIC_PRESSURE', 'PRECIPITATION', 'RELATIVE_HUMIDITY', 'SOLAR_RADIATION', 'TEMPERATURE', 'WIND_DIRECTION', 'WIND_SPEED']

MAGNITUDE_NAME,STATION_CODE,STATION_NAME,WEATHER_DATETIME,WEATHER_LATITUDE,WEATHER_LONGITUDE,WEATHER_ALTITUDE,BAROMETRIC_PRESSURE,PRECIPITATION,RELATIVE_HUMIDITY,SOLAR_RADIATION,TEMPERATURE,WIND_DIRECTION,WIND_SPEED
0,28079004,Plaza España,2023-01-01 00:00:00,40.423882,-3.712257,637,NaN,NaN,NaN,NaN,5.0,NaN,NaN
1,28079004,Plaza España,2023-01-01 01:00:00,40.423882,-3.712257,637,NaN,NaN,NaN,NaN,5.8,NaN,NaN
2,28079004,Plaza España,2023-01-01 02:00:00,40.423882,-3.712257,637,NaN,NaN,NaN,NaN,5.7,NaN,NaN
3,28079004,Plaza España,2023-01-01 03:00:00,40.423882,-3.712257,637,NaN,NaN,NaN,NaN,7.2,NaN,NaN
4,28079004,Plaza España,2023-01-01 04:00:00,40.423882,-3.712257,637,NaN,NaN,NaN,NaN,8.3,NaN,NaN

In [9]:
weather["STATION_CODE"].sample(1).iloc[0]

np.int64(28079113)

In [14]:
station = 28079008
weather.loc[
    weather["STATION_CODE"] == station
].groupby("MAGNITUDE_NAME").size().sort_values(ascending=False)

MAGNITUDE_NAME
RELATIVE HUMIDITY    1201
TEMPERATURE          1201
dtype: int64

In [17]:
for mag in weather["MAGNITUDE_NAME"].unique():
    
    subset = weather[
        weather["MAGNITUDE_NAME"] == mag
    ]
    
    values = subset[
        [f"HOUR_{i:02d}" for i in range(1,25)]
    ].stack()

    print(
        f"{mag:20s}",
        "Min:", values.min(),
        "Max:", values.max()
    )

WIND SPEED           Min: 0.0 Max: 989.29
WIND DIRECTION       Min: 0.0 Max: 360.0
TEMPERATURE          Min: -318.2 Max: 124.2
RELATIVE HUMIDITY    Min: -149.0 Max: 981.0
BAROMETRIC PRESSURE  Min: 0.0 Max: 1322.0
SOLAR RADIATION      Min: -2.0 Max: 2203.0
PRECIPITATION        Min: 0.0 Max: 38.4

In [18]:
weather.groupby("STATION_CODE")["MAGNITUDE_NAME"].nunique().sort_values(ascending=False)

STATION_CODE
28079102    7
28079106    7
28079024    7
28079059    7
28079108    7
28079103    7
28079107    7
28079054    6
28079056    6
28079039    3
28079114    2
28079113    2
28079112    2
28079111    2
28079110    2
28079109    2
28079115    2
28079104    2
28079008    2
28079058    2
28079038    2
28079036    2
28079035    2
28079016    2
28079018    1
28079004    1
Name: MAGNITUDE_NAME, dtype: int64

In [22]:
station_magnitudes = weather.groupby("STATION_CODE")["MAGNITUDE_NAME"]\
                            .unique()\
                            .reset_index()

station_magnitudes.head(30)

    STATION_CODE                                     MAGNITUDE_NAME
0       28079004                                      [TEMPERATURE]
1       28079008                   [TEMPERATURE, RELATIVE HUMIDITY]
2       28079016                   [TEMPERATURE, RELATIVE HUMIDITY]
3       28079018                                      [TEMPERATURE]
4       28079024  [WIND SPEED, WIND DIRECTION, TEMPERATURE, RELA...
5       28079035                   [TEMPERATURE, RELATIVE HUMIDITY]
6       28079036                   [TEMPERATURE, RELATIVE HUMIDITY]
7       28079038                   [TEMPERATURE, RELATIVE HUMIDITY]
8       28079039    [TEMPERATURE, RELATIVE HUMIDITY, PRECIPITATION]
9       28079054  [WIND SPEED, WIND DIRECTION, TEMPERATURE, RELA...
10      28079056  [WIND SPEED, WIND DIRECTION, TEMPERATURE, RELA...
11      28079058                   [TEMPERATURE, RELATIVE HUMIDITY]
12      28079059  [WIND SPEED, WIND DIRECTION, TEMPERATURE, RELA...
13      28079102  [WIND SPEED, WIND DIRECTION, TEMPERATURE, RELA...
14      28079103  [WIND SPEED, WIND DIRECTION, TEMPERATURE, RELA...
15      28079104                       [WIND SPEED, WIND DIRECTION]
16      28079106  [WIND SPEED, WIND DIRECTION, TEMPERATURE, RELA...
17      28079107  [WIND SPEED, WIND DIRECTION, TEMPERATURE, RELA...
18      28079108  [WIND SPEED, WIND DIRECTION, TEMPERATURE, RELA...
19      28079109                   [TEMPERATURE, RELATIVE HUMIDITY]
20      28079110                   [TEMPERATURE, RELATIVE HUMIDITY]
21      28079111                   [TEMPERATURE, RELATIVE HUMIDITY]
22      28079112                   [TEMPERATURE, RELATIVE HUMIDITY]
23      28079113                   [TEMPERATURE, RELATIVE HUMIDITY]
24      28079114                   [TEMPERATURE, RELATIVE HUMIDITY]
25      28079115                   [TEMPERATURE, RELATIVE HUMIDITY]

In [23]:
summary = (
    weather.groupby("STATION_CODE")["MAGNITUDE_NAME"]
    .agg(lambda x: sorted(x.unique()))
    .reset_index()
)

summary

    STATION_CODE                                     MAGNITUDE_NAME
0       28079004                                      [TEMPERATURE]
1       28079008                   [RELATIVE HUMIDITY, TEMPERATURE]
2       28079016                   [RELATIVE HUMIDITY, TEMPERATURE]
3       28079018                                      [TEMPERATURE]
4       28079024  [BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE ...
5       28079035                   [RELATIVE HUMIDITY, TEMPERATURE]
6       28079036                   [RELATIVE HUMIDITY, TEMPERATURE]
7       28079038                   [RELATIVE HUMIDITY, TEMPERATURE]
8       28079039    [PRECIPITATION, RELATIVE HUMIDITY, TEMPERATURE]
9       28079054  [PRECIPITATION, RELATIVE HUMIDITY, SOLAR RADIA...
10      28079056  [BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE ...
11      28079058                   [RELATIVE HUMIDITY, TEMPERATURE]
12      28079059  [BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE ...
13      28079102  [BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE ...
14      28079103  [BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE ...
15      28079104                       [WIND DIRECTION, WIND SPEED]
16      28079106  [BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE ...
17      28079107  [BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE ...
18      28079108  [BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE ...
19      28079109                   [RELATIVE HUMIDITY, TEMPERATURE]
20      28079110                   [RELATIVE HUMIDITY, TEMPERATURE]
21      28079111                   [RELATIVE HUMIDITY, TEMPERATURE]
22      28079112                   [RELATIVE HUMIDITY, TEMPERATURE]
23      28079113                   [RELATIVE HUMIDITY, TEMPERATURE]
24      28079114                   [RELATIVE HUMIDITY, TEMPERATURE]
25      28079115                   [RELATIVE HUMIDITY, TEMPERATURE]

In [25]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

summary = (
    weather.groupby("STATION_CODE")["MAGNITUDE_NAME"]
    .agg(lambda x: sorted(x.unique()))
    .reset_index()
)

summary

,STATION_CODE,MAGNITUDE_NAME
0,28079004,[TEMPERATURE]
1,28079008,"[RELATIVE HUMIDITY, TEMPERATURE]"
2,28079016,"[RELATIVE HUMIDITY, TEMPERATURE]"
3,28079018,[TEMPERATURE]
4,28079024,"[BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE HUMIDITY, SOLAR RADIATION, TEMPERATURE, WIND DIRECTION, WIND SPEED]"
5,28079035,"[RELATIVE HUMIDITY, TEMPERATURE]"
6,28079036,"[RELATIVE HUMIDITY, TEMPERATURE]"
7,28079038,"[RELATIVE HUMIDITY, TEMPERATURE]"
8,28079039,"[PRECIPITATION, RELATIVE HUMIDITY, TEMPERATURE]"
9,28079054,"[PRECIPITATION, RELATIVE HUMIDITY, SOLAR RADIATION, TEMPERATURE, WIND DIRECTION, WIND SPEED]"
10,28079056,"[BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE HUMIDITY, TEMPERATURE, WIND DIRECTION, WIND SPEED]"
11,28079058,"[RELATIVE HUMIDITY, TEMPERATURE]"
12,28079059,"[BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE HUMIDITY, SOLAR RADIATION, TEMPERATURE, WIND DIRECTION, WIND SPEED]"
13,28079102,"[BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE HUMIDITY, SOLAR RADIATION, TEMPERATURE, WIND DIRECTION, WIND SPEED]"
14,28079103,"[BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE HUMIDITY, SOLAR RADIATION, TEMPERATURE, WIND DIRECTION, WIND SPEED]"
15,28079104,"[WIND DIRECTION, WIND SPEED]"
16,28079106,"[BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE HUMIDITY, SOLAR RADIATION, TEMPERATURE, WIND DIRECTION, WIND SPEED]"
17,28079107,"[BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE HUMIDITY, SOLAR RADIATION, TEMPERATURE, WIND DIRECTION, WIND SPEED]"
18,28079108,"[BAROMETRIC PRESSURE, PRECIPITATION, RELATIVE HUMIDITY, SOLAR RADIATION, TEMPERATURE, WIND DIRECTION, WIND SPEED]"
19,28079109,"[RELATIVE HUMIDITY, TEMPERATURE]"
20,28079110,"[RELATIVE HUMIDITY, TEMPERATURE]"
21,28079111,"[RELATIVE HUMIDITY, TEMPERATURE]"
22,28079112,"[RELATIVE HUMIDITY, TEMPERATURE]"
23,28079113,"[RELATIVE HUMIDITY, TEMPERATURE]"
24,28079114,"[RELATIVE HUMIDITY, TEMPERATURE]"
25,28079115,"[RELATIVE HUMIDITY, TEMPERATURE]"